// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmjS5HtP0qoCDqpOe8qNJRraDMac9YkFE',
    appId: '1:57811204540:web:fabc0d1075273ac6a753b9',
    messagingSenderId: '57811204540',
    projectId: 'catan-board-generator-27696',
    authDomain: 'catan-board-generator-27696.firebaseapp.com',
    databaseURL:
        'https://catan-board-generator-27696-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'catan-board-generator-27696.firebasestorage.app',
    measurementId: 'G-KMYJ90LHDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHocpYGyWTWQRdL388oELxqEl7d-3LplA',
    appId: '1:57811204540:android:6e21e79dfd3c9499a753b9',
    messagingSenderId: '57811204540',
    projectId: 'catan-board-generator-27696',
    databaseURL:
        'https://catan-board-generator-27696-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'catan-board-generator-27696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBwE9MlVt4WFLZoA4Wv-ePPUUHBPtS19g',
    appId: '1:57811204540:ios:10769d3e8cdb400aa753b9',
    messagingSenderId: '57811204540',
    projectId: 'catan-board-generator-27696',
    databaseURL:
        'https://catan-board-generator-27696-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'catan-board-generator-27696.firebasestorage.app',
    iosBundleId: 'com.bengi.catanBoardGenerator',
  );
}
